let krsvData = [
	{id : 1, src : "../src/krosovki/components/item/img/white.jpg", srcMini : "../src/krosovki/components/item/img/white_1.jpg", brand : "Nike", color : "Белый", sex : "Женский", price : 1000, title : "Кроссовки Nike Old Skool 36 DX Anaheim Factory Light Blue/Purple/Pink"},
	{id : 2, src : "../src/krosovki/components/item/img/black.jpg", srcMini : "../src/krosovki/components/item/img/black_1.jpg", brand : "Nike", color : "Чёрный", sex : "Мужской", price : 7000, title : "Кроссовки Nike ERA Mother Earth Elements/Marshmallow"},
	{id : 3, src : "../src/krosovki/components/item/img/blue.jpg", srcMini : "../src/krosovki/components/item/img/blue_1.jpg", brand : "Adidas", color : "Синий", sex : "Унисекс", price : 3000, title : "Кроссовки Adidas Chuck Taylor All Star Low Peace Black/White"},
	{id : 4, src : "../src/krosovki/components/item/img/white.jpg", srcMini : "../src/krosovki/components/item/img/white_1.jpg", brand : "Nike", color : "Белый", sex : "Женский", price : 2000, title : "Кроссовки Nike Old Skool 36 DX Anaheim Factory Light Blue/Purple/Pink"},
	{id : 5, src : "../src/krosovki/components/item/img/black.jpg", srcMini : "../src/krosovki/components/item/img/black_1.jpg", brand : "Nike", color : "Чёрный", sex : "Мужской", price : 6000, title : "Кроссовки Nike ERA Mother Earth Elements/Marshmallow"},
	{id : 6, src : "../src/krosovki/components/item/img/blue.jpg", srcMini : "../src/krosovki/components/item/img/blue_1.jpg", brand : "Adidas", color : "Синий", sex : "Унисекс", price : 4000, title : "Кроссовки Adidas Chuck Taylor All Star Low Peace Black/White"},
	{id : 7, src : "../src/krosovki/components/item/img/white.jpg", srcMini : "../src/krosovki/components/item/img/white_1.jpg", brand : "Nike", color : "Белый", sex : "Женский", price : 5000, title : "Кроссовки Nike Old Skool 36 DX Anaheim Factory Light Blue/Purple/Pink"},
	{id : 8, src : "../src/krosovki/components/item/img/black.jpg", srcMini : "../src/krosovki/components/item/img/black_1.jpg", brand : "Nike", color : "Чёрный", sex : "Мужской", price : 1000, title : "Кроссовки Nike ERA Mother Earth Elements/Marshmallow"},
	{id : 9, src : "../src/krosovki/components/item/img/blue.jpg", srcMini : "../src/krosovki/components/item/img/blue_1.jpg", brand : "Adidas", color : "Синий", sex : "Унисекс", price : 1000, title : "Кроссовки Adidas Chuck Taylor All Star Low Peace Black/White"},
];

export default krsvData;